profile: '{cipher}AQBTgzq7Ye2q7kWGp/7p/St0vAsr3nl8AGq6zwxMiBSi1+wFZ1FIq8ef9/zYwtv54EP3joPLuIesC61OLbAzepIbuuuTrpNT9qPllLTwqki4H2MV+Oye9hWXiVYnwY/6kVsvmsFlNuAKztLo/bJkzLMuGVguxtaWKT06CsphCqCjUFTDEneHutZ1q+YUVlHAYLtW7mTJbqaf8ELehgoPsD6yxyB8RoKRl7ImAHVAUNiI8EE+tTjUl+dPgKo22isOA0qEFHR+UXQ0cxOITv7xmMYMtCSxLKMuTRhnS2gTd2ahpYBH4XvXPzdcVKo48Wk8U+o6Q/nQbHs1TMRamGj3HXmpm+95lSKm42mEPqvOf5/lOcSuXeTAD8IpUX1HZLACn1A='
#在Spring Cloud Config中通过在属性值前使用{cipher}前缀来标注该内容是一个加密值，当微服务客户端来加载配置时，
#配置中心会自动的为带有{cipher}前缀的值进行解密。通过该机制的实现，运维团队就可以放心的将线上信息的加密资源给到微服务团队，
#而不用担心这些敏感信息遭到泄露了。
